### ISSUE TITLE
Blocked from accessing https://gains.jaw.dev?

### ISSUE THREAD

**Issue by mckenna654** [wajeht/gains#373]
**Describe the bug**
Blocked from accessing https://gains.jaw.dev ?

iPhone 13 Pro and M1 Macbook from an Australian IP

<img width="1133" alt="image" src="https://github.com/wajeht/gains/assets/10954027/5798360c-2e1c-44b6-a2f1-34bb13f4a719">

**Comment by wajeht** [comment]
@mckenna654 sorry, try with a US vpn!

**Comment by mckenna654** [comment]
Works, any chance you can allow it for Australian IPs?
